let movieData = [
    {
      title : "아바타-물의 길",
      entitle : "Avatar: The Way of Water",
      image : "/image/movies/86072_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "1",
      runningtime : "",
      comedate : "",
      id : "0",
      rsrvrate : 82.1,
      scndstate : 1,

    },
    {
      title : "영웅",
      entitle : "",
      image : "/image/movies/83203_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "1",
      runningtime : "",
      comedate : "",
      id : "1",
      rsrvrate : 11,
      scndstate : 0,

    },
    {
      title : "올빼미",
      entitle : "",
      image : "/image/movies/86481_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "2",
      runningtime : "",
      comedate : "",
      id : "2",
      rsrvrate : 1.5,
      scndstate : 1,

    },
    {
      title : "오늘 밤, 세계에서 이 사랑이 사라진다 해도",
      entitle : "",
      image : "/image/movies/86503_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "1",
      runningtime : "",
      comedate : "",
      id : "3",
      rsrvrate : 1.3,
      scndstate : 1,

    },
    {
      title : "젠틀맨",
      entitle : "",
      image : "/image/movies/86706_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "2",
      runningtime : "",
      comedate : "",
      id : "4",
      rsrvrate : 1.0,
      scndstate : 1,

    },
    {
      title : "신비아파트 극장판 차원도깨비와 7개의 세계",
      entitle : "",
      image : "/image/movies/86670_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "0",
      runningtime : "",
      comedate : "",
      id : "5",
      rsrvrate : 0.8,
      scndstate : 1,

    },
    {
      title : "몬스터 신부-101번째 프로포즈",
      entitle : "",
      image : "/image/movies/86488_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "0",
      runningtime : "",
      comedate : "",
      id : "6",
      rsrvrate : 0.7,
      scndstate : 0,

    },
    {
      title : "눈의 여왕5-스노우 프린세스와 미러랜드의 비밀",
      entitle : "",
      image : "/image/movies/86679_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "0",
      runningtime : "",
      comedate : "",
      id : "7",
      rsrvrate : 0.6,
      scndstate : 0,

    },
    {
      title : "핑크퐁 시네마 콘서트 2-원더스타 콘서트 대작전 ",
      entitle : "",
      image : "/image/movies/86535_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "0",
      runningtime : "",
      comedate : "",
      id : "8",
      rsrvrate : 0.4,
      scndstate : 0,

    },
    {
      title : "코르사주",
      entitle : "",
      image : "/image/movies/86699_320.jpg",
      director : "",
      actor : "",
      genre : "",
      agelimit : "2",
      runningtime : "",
      comedate : "",
      id : "9",
      rsrvrate : 0.1,
      scndstate : 0,

    }
  ]

  export default movieData;